//
// Created by Doly Rakotomaheninna on 10/19/19.
//

#ifndef CODE_GENERATION_FILE_VALIDATION_SOCKET_H
#define CODE_GENERATION_FILE_VALIDATION_SOCKET_H

#endif //CODE_GENERATION_FILE_VALIDATION_SOCKET_H
